spring:
  mvc:
    date-format: yyyy-MM-dd HH:mm:ss
  jackson:
    joda-date-time-format: yyyy-MM-dd HH:mm:ss
    date-format: yyyy-MM-dd HH:mm:ss
  datasource:
    url: jdbc:mysql://paascloud-db-mysql:3306/paascloud_uac?characterEncoding=utf8&useSSL=false

mybatis:
  type-aliases-package: com.ucar.qtshop.uac.model.domain
  mapper-locations: classpath:mapper/*.xml,classpath*:sdk/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

mapper:
  mappers: com.ucar.qtshop.common.core.mybatis.MyMapper
  not-empty: false
  identity: MYSQL

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

liquibase:
  change-log: classpath:liquibase/index.xml
  user: ${spring.datasource.username}
  password: ${spring.datasource.password}
  url: ${spring.datasource.url}

security:
  oauth2:
    client:
      clientId: paascloud-client-uac
      clientSecret: paascloudClientSecret
      access-token-uri: http://paascloud-gateway:7979/uac/oauth/token
      user-authorization-uri: http://paascloud-gateway:7979/uac/oauth/authorize
    resource:
      user-info-uri: http://paascloud-gateway:7979/uac/user
      prefer-token-info: false
      jwt:
        key-uri: http://paascloud-provider-uac:8000/oauth/token_key

paascloud:
  enableSqlLogInterceptor: false
  aliyun:
    rocketMq:
      enable: true
      reliableMessageConsumer: false
      reliableMessageProducer: true
      instanceName: paascloud-provider-uac
      consumerGroup: CID_UAC
      producerGroup: PID_UAC
  token:
    interceptor:
      enable: true
  zk:
    zkAddressList: paascloud-provider-zk:2181
  auth:
    rest-pwd-url: http://dev-login.paascloud.net/resetPwd?resetPwdKey=
    active-user-url: http://dev-api.paascloud.net:7979/uac/auth/activeUser/
    refresh-token-url: http://dev-api.paascloud.net:7979/uac/oauth/token
  oauth2:
    jwtSigningKey: paascloud
    client:
      id: ${security.oauth2.resource.id}
      accessTokenUrl: ${security.oauth2.client.access-token-uri}
      clientId: ${security.oauth2.client.clientId}
      clientSecret: ${security.oauth2.client.clientSecret}
      clientAuthenticationScheme: header
      tokenStore: jwt